config/routes.rb
Rails.application.routes.draw do
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  resources :users
  root 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	validates :email , uniqueness: true, presence: true
	validates :fname, :lname , presence: true , length: {maximum: 20}
	validates :password_digest, presence: true, length: {minimum: 8, maximum: 15} 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new	
	end
	def create
		@user = User.find_by("email = ? AND password_digest = ?",params[:email],params[:password_digest])
		if @user
			session[:user_id] = @user.id
			redirect_to user_path(@user)
		else 
			redirect_to login_path
		end
	end
	def destroy
		session[:user_id] = nil
		redirect_to login_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
	end
	def new
		@user = User.new
	end
	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to users_path
		else
			render 'new'
		end 
	end
	def show
		@user = User.find(params[:id])
	end
	def edit
		@user = User.find(params[:id])
	end
	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to user_path(@user)
		else
			render 'edit'
		end
	end
	private
	def user_params
		params.require(:user).permit(:fname,:lname,:email,:password_digest)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Userlogin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this post from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<%= form_for @user do |form|%>
	<p>
		First Name : <%= form.text_field :fname %>
	</p>
	<p>
		Last Name : <%= form.text_field :lname %>
	</p>
	<p>
		Email : <%= form.email_field :email %>
	</p>
	<p>
		Password : <%= form.password_field :password_digest%>
	</p>
	<p>
		<%= form.submit "Submit" %>
	</p>
<%end%>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= render 'form'%>
<%= link_to 'Back', user_path(@user)%>

app/views/users/index.html.erb
<h1>Login Application</h1>
<%= link_to 'Signup' , new_user_path %><br>
<%= link_to 'Signin' , login_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render 'form' %>
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1>User Info</h1>
<p>
	First Name: <%= @user.fname %>
</p>
<p>
	Last Name : <%= @user.lname%>
</p>
<p>
	Email : <%= @user.email%>
</p>
<%= link_to 'Logout', logout_path%>
<%= link_to 'Edit', edit_user_path(@user) %>